name: wefilling
description: "함께하면 즐거운 대학 생활 - 위필링"
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.2+9

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  
  # Firebase
  firebase_core: ^4.1.0
  firebase_auth: ^6.0.2
  firebase_messaging: ^16.0.2
  firebase_crashlytics: ^5.0.2
  firebase_storage: ^13.0.1
  firebase_remote_config: ^6.0.1
  cloud_firestore: ^6.0.1
  cloud_functions: ^6.0.2
  
  # Social Login
  google_sign_in: ^7.2.0
  sign_in_with_apple: ^6.1.3
  
  # UI & Utilities
  cupertino_icons: ^1.0.8
  provider: ^6.0.5  # 상태 관리용
  flutter_local_notifications: ^18.0.1
  permission_handler: ^11.3.1
  intl: ^0.20.2
  url_launcher: ^6.1.14
  shared_preferences: ^2.2.2
  webview_flutter: ^4.4.2
  image_picker: ^1.0.4
  uuid: ^4.5.1
  flutter_image_compress: ^2.1.0
  path_provider: ^2.1.1
  path: ^1.8.3
  http: ^1.1.0
  translator: ^1.0.3+1
  flutter_linkify: ^6.0.0
  google_fonts: ^6.1.0
  cached_network_image: ^3.4.1
  
  # Cache
  hive: ^2.2.3
  hive_flutter: ^1.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.14.3
  flutter_lints: ^2.0.3
  
  # Code Generation
  hive_generator: ^2.0.1
  build_runner: ^2.4.0

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icons/app_logo.png"
  # iOS는 여백이 있는 버전 사용 (잘림 방지)
  image_path_ios: "assets/icons/app_logo_ios.png"
  # Android는 원본 사용
  image_path_android: "assets/icons/app_logo.png"
  adaptive_icon_background: "#FFFFFF"
  adaptive_icon_foreground: "assets/icons/app_logo.png"
  remove_alpha_ios: true

flutter:
  generate: true  # Add this line for l10n support
  config:
    enable-lldb-debugging: false

  uses-material-design: true

  assets:
      - assets/
      - assets/icons/
      - assets/images/

  fonts:
    - family: Roboto
      fonts:
        - asset: assets/fonts/Roboto/Roboto-Regular.ttf
          weight: 400
        - asset: assets/fonts/Roboto/Roboto-Bold.ttf
          weight: 700
        - asset: assets/fonts/Roboto/Roboto-Black.ttf
          weight: 900
    - family: Pretendard
      fonts:
        - asset: assets/fonts/Pretendard/PretendardJP-Thin.otf
          weight: 100
        - asset: assets/fonts/Pretendard/PretendardJP-ExtraLight.otf
          weight: 200
        - asset: assets/fonts/Pretendard/PretendardJP-Light.otf
          weight: 300
        - asset: assets/fonts/Pretendard/PretendardJP-Regular.otf
          weight: 400
        - asset: assets/fonts/Pretendard/PretendardJP-Medium.otf
          weight: 500
        - asset: assets/fonts/Pretendard/PretendardJP-SemiBold.otf
          weight: 600
        - asset: assets/fonts/Pretendard/PretendardJP-Bold.otf
          weight: 700
        - asset: assets/fonts/Pretendard/PretendardJP-ExtraBold.otf
          weight: 800
        - asset: assets/fonts/Pretendard/PretendardJP-Black.otf
          weight: 900
    - family: HancomMalrangmalrang
      fonts:
        - asset: assets/fonts/HancomMalrangmalrang/HancomMalangMalang-Regular.otf
          weight: 400
        - asset: assets/fonts/HancomMalrangmalrang/HancomMalangMalang-Bold.otf
          weight: 700
